apiVersion: v1
kind: Secret
metadata:
  name: secret-lab
type: Opaque
data:
  .secret-file: UGFzc3dvcmQxMjM= # base64 encoded password123
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-lab-pod
spec:
  volumes:
  - name: secret-lab-volume
    secret:
      secretName: secret-lab
  containers:
  - name: secret-test-container
    image: registry.k8s.io/busybox
    command:
    - ls # list the files in the mounted secret volume
    - "-l" # list the files in the mounted secret volume
    - "/etc/secret-lab-volume" # list the files in the mounted secret volume
    volumeMounts:
    - name: secret-lab-volume
      readOnly: true
      mountPath: "/etc/secret-lab-volume"