apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-todo-app
  labels:
    app: simple-todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-todo-app
  template:
    metadata:
      labels:
        app: simple-todo-app
    spec:
      containers:
        - name: simple-todo-app
          image: acrbragr.azurecr.io/simple-todo-app:v1
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: simple-todo-app-service
spec:
  selector:
    app: simple-todo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
