# Usar una imagen oficial de Node.js como base
FROM node:latest

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar archivos de dependencia y instalar paquetes
COPY package.json package-lock.json ./ 
RUN npm install

# Copiar el resto de los archivos
COPY . .

# Exponer el puerto en el que se ejecuta la aplicación
EXPOSE 3000

# Comando para iniciar la aplicación
CMD ["npm", "start"]
