apiVersion: apps/v1
kind: Deployment
metadata:
  name: sitio1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sitio1
  template:
    metadata:
      labels:
        app: sitio1
    spec:
      containers:
      - name: sitio1
        image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
        ports:
        - containerPort: 80
        env:
        - name: TITLE
          value: "Bienvenidos al Sitio 1"
---
apiVersion: v1
kind: Service
metadata:
  name: sitio1 
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: sitio1